### ISSUE TITLE
A way to use interceptors

### ISSUE THREAD

**Issue by leonardosalles** [ganey/ionic-native-http-angular-wrapper#2]
Is there a way to use interceptors? Or we just need to set common headers in a request builder?

**Comment by ganey** [comment]
I'm not sure the nativeHttp supports the interceptors at all, so you would have to set the common headers.

You could use the native's setHeader to set them for all future requests, `httpWrapper.nativeHttp.setHeader('Hostname', 'Header', 'Value')` 
but the headers end up persistent https://github.com/silkimen/cordova-plugin-advanced-http#setheader

I haven't tried interceptors with Angular 5 yet either as the angular/common/http changes have thrown me a bit. 
I usually end up with typescript errors about the return type as I can't seem to pin down which method it actually uses: https://github.com/angular/angular/blob/5.0.5/packages/common/http/src/client.ts#L673

I'm more than happy to accept PR's if you come up with anything though.

Sorry I haven't been very helpful.

**Comment by leonardosalles** [comment]
Sure, it is very clear, so my idea is to create a provider that generate the request with my common headers ; )
